package modelsDefine

/*
	模型枚举文件，请勿修改！
*/
const MDRepository_ID string = "id"
const MDRepository_OwnerID string = "owner_id"
const MDRepository_LowerName string = "lower_name"
const MDRepository_Name string = "name"
const MDRepository_Description string = "description"
const MDRepository_Website string = "website"
const MDRepository_DefaultBranch string = "default_branch"
const MDRepository_Size string = "size"
const MDRepository_UseCustomAvatar string = "use_custom_avatar"
const MDRepository_NumWatches string = "num_watches"
const MDRepository_NumStars string = "num_stars"
const MDRepository_NumForks string = "num_forks"
const MDRepository_NumIssues string = "num_issues"
const MDRepository_NumClosedIssues string = "num_closed_issues"
const MDRepository_NumPulls string = "num_pulls"
const MDRepository_NumClosedPulls string = "num_closed_pulls"
const MDRepository_NumMilestones string = "num_milestones"
const MDRepository_NumClosedMilestones string = "num_closed_milestones"
const MDRepository_IsPrivate string = "is_private"
const MDRepository_IsBare string = "is_bare"
const MDRepository_IsMirror string = "is_mirror"
const MDRepository_EnableWiki string = "enable_wiki"
const MDRepository_AllowPublicWiki string = "allow_public_wiki"
const MDRepository_EnableExternalWiki string = "enable_external_wiki"
const MDRepository_ExternalWikiURL string = "external_wiki_url"
const MDRepository_EnableIssues string = "enable_issues"
const MDRepository_AllowPublicIssues string = "allow_public_issues"
const MDRepository_EnableExternalTracker string = "enable_external_tracker"
const MDRepository_ExternalTrackerURL string = "external_tracker_url"
const MDRepository_ExternalTrackerFormat string = "external_tracker_format"
const MDRepository_ExternalTrackerStyle string = "external_tracker_style"
const MDRepository_EnablePulls string = "enable_pulls"
const MDRepository_PullsIgnoreWhitespace string = "pulls_ignore_whitespace"
const MDRepository_PullsAllowRebase string = "pulls_allow_rebase"
const MDRepository_IsFork string = "is_fork"
const MDRepository_ForkID string = "fork_id"
const MDRepository_CreatedUnix string = "created_unix"
const MDRepository_UpdatedUnix string = "updated_unix"
